# Manage related routes
_poll_manage_edit:
    pattern: /admin/poll/edit/{id}
    defaults: { _controller: Desarrolla2PollBundle:Manage:edit }

_poll_manage_remove:
    pattern: /admin/poll/remove/{id}
    defaults: { _controller: Desarrolla2PollBundle:Manage:remove }

_poll_manage_add:
    pattern: /admin/poll/add
    defaults: { _controller: Desarrolla2PollBundle:Manage:add }

_poll_manage_list:
    pattern: /admin/poll/list
    defaults: { _controller: Desarrolla2PollBundle:Manage:list }


# Option manage related routes
_poll_manage_option_edit:
    pattern: /admin/poll/option/edit/{id}
    defaults: { _controller: Desarrolla2PollBundle:ManageOption:edit }

_poll_manage_option_remove:
    pattern: /admin/poll/option/remove/{id}
    defaults: { _controller: Desarrolla2PollBundle:ManageOption:remove }

_poll_manage_option_add:
    pattern: /admin/poll/option/add/{id}
    defaults: { _controller: Desarrolla2PollBundle:ManageOption:add }

_poll_manage_options:
    pattern: /admin/poll/list/option/{id}
    defaults: { _controller: Desarrolla2PollBundle:ManageOption:list }


# Show related routes
_poll_report:
    pattern: /poll/report/{id}
    defaults: { _controller: Desarrolla2PollBundle:Polls:report, id: 1 }

_poll_show:
    pattern: /poll/{id}/{slug}
    defaults: { _controller: Desarrolla2PollBundle:Polls:show, id: 1, slug: "" }

_poll_index:
    pattern: /polls
    defaults: { _controller: Desarrolla2PollBundle:Polls:index }