<?php

namespace Desarrolla2\PollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PollOptionHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollOptionHitRepository extends EntityRepository
{
}